import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type {
  BudgetCategoryRow,
  ItineraryActivityRow,
  ItineraryDayRow,
  TripRow,
} from '@/types/database';

type ItineraryDay = ItineraryDayRow & { activities: ItineraryActivityRow[] };

export async function exportTripPdf(params: {
  trip: TripRow;
  itinerary: ItineraryDay[];
  budget: BudgetCategoryRow[];
}): Promise<void> {
  const { trip, itinerary, budget } = params;
  const total = budget.reduce((s, c) => s + Number(c.amount_usd), 0);

  const itineraryHtml = itinerary
    .map(
      (d) => `
      <h3>Day ${d.day_number}${d.title ? ` · ${d.title}` : ''}</h3>
      <ul>
        ${d.activities
          .map(
            (a) =>
              `<li><strong>${a.activity_time ?? ''}</strong> ${a.name} — $${Number(a.cost_usd ?? 0)} · ${a.transport ?? ''}</li>`,
          )
          .join('')}
      </ul>`,
    )
    .join('');

  const budgetHtml = budget
    .map((c) => `<tr><td>${c.label}</td><td>$${Number(c.amount_usd).toFixed(0)}</td></tr>`)
    .join('');

  const html = `
    <html>
      <head><meta charset="utf-8"><style>
        body { font-family: system-ui, sans-serif; padding: 24px; color: #0f172a; }
        h1 { color: #0284c7; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        td { padding: 8px; border-bottom: 1px solid #e2e8f0; }
      </style></head>
      <body>
        <h1>${trip.title}</h1>
        <p>${trip.destination} · ${trip.start_date ?? 'TBD'} – ${trip.end_date ?? 'TBD'}</p>
        <p>Budget total: <strong>$${total.toFixed(0)} USD</strong></p>
        <h2>Itinerary</h2>
        ${itineraryHtml || '<p>No itinerary yet.</p>'}
        <h2>Budget</h2>
        <table>${budgetHtml}</table>
        <p style="margin-top:32px;color:#64748b;font-size:12px;">Generated by TravelAI</p>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `${trip.title} itinerary`,
    });
  }
}
